const COMMENT_MAX_LENGTH = 140;
const HASHTAGS_MAX_NUMBER = 5;
const NUMBER_OF_PHOTOES = 25;
const COMMENT_PARTITION_SIZE = 5;

export { COMMENT_MAX_LENGTH, NUMBER_OF_PHOTOES, HASHTAGS_MAX_NUMBER, COMMENT_PARTITION_SIZE };
